INSERT INTO POLIZA (ID, TIPO, ESTADO) VALUES (1, 'vida', 'activa');
INSERT INTO POLIZA (ID, TIPO, ESTADO) VALUES (2, 'hogar', 'activa');

INSERT INTO RIESGO (ID, POLIZA_ID, ESTADO) VALUES (1, 1, 'activo');
INSERT INTO RIESGO (ID, POLIZA_ID, ESTADO) VALUES (2, 1, 'activo');